var institution_type = ["Unknown","Association",
"Center",
"College",
"Company",
"Consortium",
"Department",
"Division",
"Foundation",
"Funding Organization",
"Government Agency",
"Hospital",
"Institute",
"Laboratory",
"Library",
"Museum",
"Program",
"Publisher",
"Research organization",
"School",
"Student Organization",
"University"];

var states = ["select a state", "AK",
"AL",
"0ALL",
"AR",
"AS",
"AZ",
"CA",
"CO",
"CT",
"DC",
"DE",
"FL",
"GA",
"GU",
"HI",
"IA",
"ID",
"IL",
"IN",
"KS",
"KY",
"LA",
"MA",
"MD",
"ME",
"MI",
"MN",
"MO",
"MP",
"MS",
"MT",
"NC",
"ND",
"NE",
"NH",
"NJ",
"NM",
"NV",
"NY",
"OH",
"OK",
"OR",
"PA",
"PR",
"RI",
"SC",
"SD",
"TN",
"TX",
"UM",
"UT",
"VA",
"VI",
"VT",
"WA",
"WI",
"WV",
"WY"];

var countries = ["Unknown","Afghanistan",
                 "Albania",
                 "Algeria",
                 "American Samoa",
                 "Andorra",
                 "Angola",
                 "Anguilla",
                 "Antarctica",
                 "Antigua and Barbuda",
                 "Argentina",
                 "Armenia",
                 "Australia",
                 "Austria",
                 "Azerbaijan",
                 "Bahamas",
                 "Bahrain",
                 "Bangladesh",
                 "Barbados",
                 "Belarus",
                 "Belgium",
                 "Belize",
                 "Benin",
                 "Bermuda",
                 "Bhutan",
                 "Bolivia, Plurinational State of",
                 "Bosnia and Herzegovina",
                 "Botswana",
                 "Bouvet Island",
                 "Brazil",
                 "British Indian Ocean Territory",
                 "Brunei Darussalam",
                 "Bulgaria",
                 "Burkina Faso",
                 "Burundi",
                 "Cambodia",
                 "Cameroon",
                 "Canada",
                 "Cape Verde",
                 "Cayman Islands",
                 "Central African Republic",
                 "Chad",
                 "Chile",
                 "China",
                 "Christmas Island",
                 "Cocos (Keeling) Islands",
                 "Colombia",
                 "Comoros",
                 "Congo",
                 "Congo, the Democratic Republic of the",
                 "Cook Islands",
                 "Costa Rica",
                 "Cote d'Ivoire",
                 "Croatia",
                 "Cuba",
                 "Cyprus",
                 "Czech Republic",
                 "Denmark",
                 "Djibouti",
                 "Dominica",
                 "Dominican Republic",
                 "Ecuador",
                 "Egypt",
                 "El Salvador",
                 "Equatorial Guinea",
                 "Eritrea",
                 "Estonia",
                 "Ethiopia",
                 "Falkland Islands (Malvinas)",
                 "Faroe Islands",
                 "Fiji",
                 "Finland",
                 "France",
                 "French Guiana",
                 "French Polynesia",
                 "French Southern Territories",
                 "Gabon",
                 "Gambia",
                 "Georgia",
                 "Germany",
                 "Ghana",
                 "Gibraltar",
                 "Greece",
                 "Greenland",
                 "Grenada",
                 "Guadeloupe",
                 "Guam",
                 "Guatemala",
                 "Guinea",
                 "Guinea-Bissau",
                 "Guyana",
                 "Haiti",
                 "Heard Island and McDonald Islands",
                 "Holy See (Vatican City State)",
                 "Honduras",
                 "Hong Kong",
                 "Hungary",
                 "Iceland",
                 "India",
                 "Indonesia",
                 "Iran, Islamic Republic of",
                 "Iraq",
                 "Ireland",
                 "Israel",
                 "Italy",
                 "Jamaica",
                 "Japan",
                 "Jordan",
                 "Kazakhstan",
                 "Kenya",
                 "Kiribati",
                 "Korea, Democratic People's Republic of",
                 "Korea, Republic of",
                 "Kuwait",
                 "Kyrgyzstan",
                 "Lao People's Democratic Republic",
                 "Latvia",
                 "Lebanon",
                 "Lesotho",
                 "Liberia",
                 "Libyan Arab Jamahiriya",
                 "Liechtenstein",
                 "Lithuania",
                 "Luxembourg",
                 "Macao",
                 "Macedonia, the former Yugoslav Republic of",
                 "Madagascar",
                 "Malawi",
                 "Malaysia",
                 "Maldives",
                 "Mali",
                 "Malta",
                 "Marshall Islands",
                 "Martinique",
                 "Mauritania",
                 "Mauritius",
                 "Mayotte",
                 "Mexico",
                 "Micronesia, Federated States of",
                 "Moldova, Republic of",
                 "Monaco",
                 "Mongolia",
                 "Montserrat",
                 "Morocco",
                 "Mozambique",
                 "Myanmar",
                 "Namibia",
                 "Nauru",
                 "Nepal",
                 "Netherlands",
                 "Netherlands Antilles",
                 "New Caledonia",
                 "New Zealand",
                 "Nicaragua",
                 "Niger",
                 "Nigeria",
                 "Niue",
                 "Norfolk Island",
                 "Northern Mariana Islands",
                 "Norway",
                 "Not Applicable",
                 "Oman",
                 "Pakistan",
                 "Palau",
                 "Palestinian Territory, Occupied",
                 "Panama",
                 "Papua New Guinea",
                 "Paraguay",
                 "Peru",
                 "Philippines",
                 "Pitcairn",
                 "Poland",
                 "Portugal",
                 "Puerto Rico",
                 "Qatar",
                 "Reunion",
                 "Romania",
                 "Russian Federation",
                 "Rwanda",
                 "Saint Helena",
                 "Saint Kitts and Nevis",
                 "Saint Lucia",
                 "Saint Pierre and Miquelon",
                 "Saint Vincent and the Grenadines",
                 "Samoa",
                 "San Marino",
                 "Sao Tome and Principe",
                 "Saudi Arabia",
                 "Senegal",
                 "Serbia and Montenegro",
                 "Seychelles",
                 "Sierra Leone",
                 "Singapore",
                 "Slovakia",
                 "Slovenia",
                 "Solomon Islands",
                 "Somalia",
                 "South Africa",
                 "South Georgia and the South Sandwich Islands",
                 "Spain",
                 "Sri Lanka",
                 "Sudan",
                 "Suriname",
                 "Svalbard and Jan Mayen",
                 "Swaziland",
                 "Sweden",
                 "Switzerland",
                 "Syrian Arab Republic",
                 "Taiwan, Province of China",
                 "Tajikistan",
                 "Tanzania, United Republic of",
                 "Thailand",
                 "Timor-Leste",
                 "Togo",
                 "Tokelau",
                 "Tonga",
                 "Trinidad and Tobago",
                 "Tunisia",
                 "Turkey",
                 "Turkmenistan",
                 "Turks and Caicos Islands",
                 "Tuvalu",
                 "Uganda",
                 "Ukraine",
                 "United Arab Emirates",
                 "United Kingdom",
                 "United States",
                 "United States Minor Outlying Islands",
                 "Uruguay",
                 "Uzbekistan",
                 "Vanuatu",
                 "Venezuela, Bolivarian Republic of",
                 "Viet Nam",
                 "Virgin Islands, British",
                 "Virgin Islands, U.S.",
                 "Wallis and Futuna",
                 "Western Sahara",
                 "Yemen",
                 "Zambia",
                 "Zimbabwe"];


function getStates(type) {

	var sel = document.getElementById("state");
	for(var i = 0; i < states.length; i++) {
	    var opt = document.createElement('option');
	    opt.innerHTML = states[i];
	    opt.value = states[i];
	    if(opt.value == type) {opt.selected = true;}
	    sel.appendChild(opt);	
	}
}

function getCountries(type) {

	var sel = document.getElementById("country");
	for(var i = 0; i < countries.length; i++) {
	    var opt = document.createElement('option');
	    opt.innerHTML = countries[i];
	    opt.value = countries[i];
	    if(opt.value == type) {opt.selected = true;}
	    sel.appendChild(opt);	
	}
 
}

function getInstitution_type(type) {
	var sel = document.getElementById("institution_type");
	for(var i = 0; i < institution_type.length; i++) {
	    var opt = document.createElement('option');
	    opt.innerHTML = institution_type[i];
	    opt.value = institution_type[i];
	    if(opt.value == type) {opt.selected = true;}
	    sel.appendChild(opt);	
	}
}
